language: python
python:
  - "3.6"
before_install:
  - pip install -r requirements.txt
  - pip install -r requirements_build.txt
jobs:
  include:
    - stage: Tests
      script:
        - "pylint sources/"
        - "PYTHONPATH=sources/ pytest tests/unit_tests"
