language: python
python:
  - "3.6"
before_install:
  - pip install -r requirements.txt
  - pip install -r requirements_build.txt
jobs:
  include:
    - stage: linter
      script:
        - "pylint sources/"
    - stage: unit_tests
      script:
        - "PYTHONPATH=sources/ pytest tests/unit_tests"
    - stage: component_tests
      script:
        - "PYTHONPATH=sources/ pytest tests/component_tests"
