language: python
python:
  - "3.6"
services:
  - docker
before_install:
  - docker-compose up -d
jobs:
  include:
    - stage: linter
      script:
        - "pylint sources/"
    - stage: unit_tests
      script:
        - "PYTHONPATH=sources pytest tests/unit_tests"
    - stage: component_tests
      script:
        - "PYTHONPATH=sources pytest tests/component_tests"
