language: python
python:
  - "3.6"
before_install:
  - pip install -r requirements.txt
  - pip install -r requirements_build.txt
  - pip install codeclimate-test-reporter
jobs:
  include:
    - stage: Tests
      script:
        - "pylint sources/"
        - "PYTHONPATH=sources pytest --cov-report html --cov=sources tests/unit_tests"
      after_success:
        - codeclimate-test-reporter --file .coverage
